"""Soyut veri erişim arayüzü (DuckDB→Postgres geçişi için tek sınır).

İş mantığı (ingest, analytics) yalnız bu Protocol'e bağlıdır; somut DuckDB'yi
import etmez. G2/G3'te ingest/sorgu metotları eklenir.
"""
from __future__ import annotations

from typing import Protocol


class Repository(Protocol):
    def connect(self) -> None: ...
    def close(self) -> None: ...
    def init_schema(self) -> None: ...
    def reset(self) -> None: ...
    def insert_events(self, rows: list[dict], source_file: str) -> int: ...
    def upsert_production(self, rows: list[dict]) -> int: ...
    def upsert_orders(self, rows: list[dict]) -> int: ...
    def count(self, table: str) -> int: ...
    def fetch_events(self, frm: str | None = None, to: str | None = None) -> list[dict]: ...
    def fetch_production(self) -> list[dict]: ...
